version: '3.4'

services:
  docker1.app:
    container_name: "docker1app-container"
    ports:
     - 5001:8080
    environment:
     - Microservices:ProductsBaseUrl=http://docker2.app:8080
     - ConnectionStrings:SqlServer=Server=sqlserver.db,1433;Database=StockDb;User=Sa;Password=Password12*;Trusted_Connection=False;TrustServerCertificate=True;Integrated Security=False
     - ConnectionStrings:RabbitMQ=rabbitmq
    depends_on:
      - sqlserver.db
  docker2.app:
   container_name: "docker2app-container"
   ports:
    - 5002:8080 
   environment:
    - ConnectionStrings:RabbitMQ=rabbitmq 
  sqlserver.db:
   user: root
   volumes:
    - c:/ImageSqlServerData:/var/opt/mssql/data
   environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Password12*
    - MSSQL_PID=Evaluation
   ports:
    - 1433:1433 
  rabbitmq :
   ports:
    - 5672:5672
    - 15672:15672
    
